/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using template emitter:
 *      SOM Emitter emitctm: 2.23.1.9
 */

#ifndef SOM_Module_rdesktop_Source
#define SOM_Module_rdesktop_Source
#endif
#define Rdesktop_Class_Source
#define M_Rdesktop_Class_Source

#include "rdesktop.ih"


SOM_Scope void  SOMLINK RD_rdInsertSettingsPages(Rdesktop *somSelf, 
                                                 HWND hwndDlg)
{
    PAGEINFO  stPI = { 0 };
    ULONG     ulPageId;
    CHAR      acName[128];
    CHAR      acPage[64] = "1/2";
    PCHAR     pcPageN;
    HAB       hab = WinQueryAnchorBlock( HWND_DESKTOP );
    CHAR      acHelpFile[CCHMAXPATH];

    RD_rdGetHelpFile( somSelf, acHelpFile );

    stPI.cb                  = sizeof(PAGEINFO);
    stPI.usPageInsertFlags   = BKA_FIRST;
    stPI.resid               = utilGetModuleHandle();
    stPI.pszName             = acName;
    stPI.pCreateParams       = (PVOID)somSelf;
    stPI.pszHelpLibraryName  = acHelpFile;

    // Load status text "Page 1 of 2"
    WinLoadString( hab, stPI.resid, IDS_PAGE_NO, sizeof(acPage), acPage );
    pcPageN = strchr( acPage, '1' );
    if ( pcPageN == NULL )
      pcPageN = acPage;

    // Redirection - page 2/2

    WinLoadString( hab, stPI.resid, IDS_REDIRECTION, sizeof(acName),
                   acName );
    stPI.usPageStyleFlags    = BKA_MINOR | BKA_STATUSTEXTON;
    stPI.pfnwp               = nbPageRedirection2;
    stPI.dlgid               = IDDLG_PAGE_REDIRECTION2;
    stPI.idDefaultHelpPanel  = IDHELP_NB_REDIRECTION2;
    ulPageId = _wpInsertSettingsPage( somSelf, hwndDlg, &stPI );
    *pcPageN = '2';
    WinSendMsg( hwndDlg, BKM_SETSTATUSLINETEXT, MPFROMLONG( ulPageId ),
                MPFROMP( acPage ) );

    // Redirection - page 1/2

    stPI.usPageStyleFlags    = BKA_MAJOR | BKA_STATUSTEXTON;
    stPI.pfnwp               = nbPageRedirection1;
    stPI.dlgid               = IDDLG_PAGE_REDIRECTION1;
    stPI.idDefaultHelpPanel  = IDHELP_NB_REDIRECTION1;
    ulPageId = _wpInsertSettingsPage( somSelf, hwndDlg, &stPI );
    *pcPageN = '1';
    WinSendMsg( hwndDlg, BKM_SETSTATUSLINETEXT, MPFROMLONG( ulPageId ),
                MPFROMP( acPage ) );

    // Protocol - page 2/2

    WinLoadString( hab, stPI.resid, IDS_PROTOCOL, sizeof(acName),
                   acName );
    stPI.usPageStyleFlags    = BKA_MINOR | BKA_STATUSTEXTON;
    stPI.pfnwp               = nbPageProtocol2;
    stPI.dlgid               = IDDLG_PAGE_PROTOCOL2;
    stPI.idDefaultHelpPanel  = IDHELP_NB_PROTOCOL2;
    ulPageId = _wpInsertSettingsPage( somSelf, hwndDlg, &stPI );
    *pcPageN = '2';
    WinSendMsg( hwndDlg, BKM_SETSTATUSLINETEXT, MPFROMLONG( ulPageId ),
                MPFROMP( acPage ) );

    // Protocol - page 1/2

    WinLoadString( hab, stPI.resid, IDS_PROTOCOL, sizeof(acName),
                   acName );
    stPI.usPageStyleFlags    = BKA_MAJOR | BKA_STATUSTEXTON;
    stPI.pfnwp               = nbPageProtocol1;
    stPI.dlgid               = IDDLG_PAGE_PROTOCOL1;
    stPI.idDefaultHelpPanel  = IDHELP_NB_PROTOCOL1;
    ulPageId = _wpInsertSettingsPage( somSelf, hwndDlg, &stPI );
    *pcPageN = '1';
    WinSendMsg( hwndDlg, BKM_SETSTATUSLINETEXT, MPFROMLONG( ulPageId ),
                MPFROMP( acPage ) );

    // Server

    WinLoadString( hab, stPI.resid, IDS_SERVER, sizeof(acName),
                   acName );
    stPI.usPageStyleFlags    = BKA_MAJOR;
    stPI.pfnwp               = nbPageServer;
    stPI.dlgid               = IDDLG_PAGE_SERVER;
    stPI.idDefaultHelpPanel  = IDHELP_NB_SERVER;
    ulPageId = _wpInsertSettingsPage( somSelf, hwndDlg, &stPI );
}

SOM_Scope BOOL  SOMLINK RD_rdDiskRedirAdd(Rdesktop *somSelf, 
                                          PSZ pszName, PSZ pszLocalPath)
{
    ULONG        ulIdx;
    PDISKREDIR   pDiskRedir, pNewBuf;
    RdesktopData *somThis = RdesktopGetData(somSelf);
    BOOL         fFound = FALSE;

    if ( ( pszName == NULL ) || ( *pszName == '\0' ) ||
         ( pszLocalPath == NULL ) || ( *pszLocalPath == '\0' ) )
      return FALSE;

    // Avoid duplicates (look for the name in sequence).
    for( ulIdx = 0; ulIdx < _seqDiskRedir._length; ulIdx++ )
    {
      pDiskRedir = &_seqDiskRedir._buffer[ulIdx];
      if ( stricmp( pDiskRedir->acName, pszName ) == 0 )
      {
        fFound = TRUE;
        break;
      }
    }

    if ( fFound )
    {
      utilWPFreeMem( somSelf, pDiskRedir->pszPath );
    }
    else
    {
      // Expand sequence.
      if ( _seqDiskRedir._length == _seqDiskRedir._maximum )
      {
        pNewBuf = (PDISKREDIR)_wpAllocMem( somSelf,
                       (_seqDiskRedir._maximum + 8) * sizeof(DISKREDIR), NULL );
        if ( pNewBuf == NULL )
          return FALSE;

        memcpy( pNewBuf, _seqDiskRedir._buffer,
                _seqDiskRedir._maximum * sizeof(DISKREDIR) );
        utilWPFreeMem( somSelf, _seqDiskRedir._buffer );
        _seqDiskRedir._buffer = pNewBuf;
        _seqDiskRedir._maximum += 8;
      }

      // Fill a new record.
      pDiskRedir = &_seqDiskRedir._buffer[_seqDiskRedir._length];
      strlcpy( pDiskRedir->acName, pszName, 8 );
      _seqDiskRedir._length++;
    }

    pDiskRedir->pszPath = (PSZ)_wpAllocMem( somSelf,
                                            strlen( pszLocalPath ) + 1, NULL );
    if ( pDiskRedir->pszPath == NULL )
      return FALSE;
    strcpy( pDiskRedir->pszPath, pszLocalPath );

    return TRUE;
}

SOM_Scope void  SOMLINK RD_rdDiskRedirDelete(Rdesktop *somSelf, 
                                             PSZ pszName)
{
    ULONG        ulIdx;
    PDISKREDIR   pDiskRedir;
    RdesktopData *somThis = RdesktopGetData(somSelf);

    for( ulIdx = 0; ulIdx < _seqDiskRedir._length; ulIdx++ )
    {
      pDiskRedir = &_seqDiskRedir._buffer[ulIdx];

      if ( ( pszName != NULL ) &&
           ( stricmp( pDiskRedir->acName, pszName ) != 0 ) )
        continue;

      utilWPFreeMem( somSelf, pDiskRedir->pszPath );

      _seqDiskRedir._length--;
      _seqDiskRedir._buffer[ulIdx] =
        _seqDiskRedir._buffer[_seqDiskRedir._length];
      if ( pszName != NULL )
        break;
    }
}

SOM_Scope void  SOMLINK RD_rdDiskRedirDeleteAll(Rdesktop *somSelf)
{
    RdesktopData *somThis = RdesktopGetData(somSelf);
    ULONG        ulIdx;

    for( ulIdx = 0; ulIdx < _seqDiskRedir._length; ulIdx++ )
      utilWPFreeMem( somSelf, _seqDiskRedir._buffer[ulIdx].pszPath );

    utilWPFreeMem( somSelf, _seqDiskRedir._buffer );

    _seqDiskRedir._length = 0;
    _seqDiskRedir._maximum = 0;
    _seqDiskRedir._buffer = NULL;
}

/*
 * Restores an ASCIIZ instance data string, allocates memory for the new
 * string, de-allocates old memory block if it is not a NULL. If KEY not
 * found string will be not changed and FALSE will be returned.
 */

SOM_Scope BOOL  SOMLINK RD_rdRestoreStringNew(Rdesktop *somSelf, 
                                              ULONG ulKey, PSZ* ppszValue)
{
    ULONG        cbValue;
    PSZ          pszValue;

    if ( !_wpRestoreString( somSelf, somCN_Rdesktop, ulKey, NULL, &cbValue ) )
      return FALSE;

    cbValue++;
    pszValue = (string)_wpAllocMem( somSelf, cbValue, NULL );
    if ( ( pszValue == NULL ) ||
         !_wpRestoreString(somSelf, somCN_Rdesktop, ulKey, pszValue, &cbValue) )
      return FALSE;

    if ( *ppszValue != NULL )
      utilWPFreeMem( somSelf, *ppszValue );
    *ppszValue = pszValue;

    return TRUE;
}

/*
 * Called by wpSetup to search KEY in the setup string and return string
 * value for this KEY. if KEY found: allocates memory for the new string,
 * de-allocates old memory block (if it is not a NULL) and returns TRUE.
 */

SOM_Scope BOOL  SOMLINK RD_rdSetupStringNew(Rdesktop *somSelf, 
                                            PSZ pszSetupString, 
                                            PSZ pszKey, PSZ* ppszValue)
{
    ULONG        cbValue;
    PSZ          pszValue;

    /* [Documentation] It's not clear for me about "plus one"...
       The actual length of the returned string, plus one for the NULL
       terminator, or the size of the buffer required if pszValue is NULL or
       the input value of pcbValue is too small.
    */
    if ( !_wpScanSetupString( somSelf, pszSetupString, pszKey, NULL, &cbValue ) )
      return FALSE;

    cbValue++;
    pszValue = (string)_wpAllocMem( somSelf, cbValue + 1, NULL );
    if ( pszValue == NULL )
      return FALSE;

    if ( !_wpScanSetupString( somSelf, pszSetupString, pszKey, pszValue,
                              &cbValue ) )
    {
      utilWPFreeMem( somSelf, pszValue );
      return FALSE;
    }

    if ( *ppszValue != NULL )
      utilWPFreeMem( somSelf, *ppszValue );
    *ppszValue = pszValue;

    return TRUE;
}

/*
 * Called by wpSetup to search KEY in the setup string and return ULONG
 * value for this KEY. If KEY not found: value will not be changed, result
 * code is FALSE.
 */

SOM_Scope BOOL  SOMLINK RD_rdSetupReadULong(Rdesktop *somSelf, 
                                            PSZ pszSetupString, 
                                            PSZ pszKey, ULONG* pulValue)
{
    CHAR     acBuf[32];
    ULONG    cbBuf;
    PCHAR    pcEnd;

    cbBuf = sizeof(acBuf);
    if ( !_wpScanSetupString( somSelf, pszSetupString, pszKey, acBuf, &cbBuf ) )
      return FALSE;

    *pulValue = (ULONG)strtol( acBuf, &pcEnd, 0 );

    return pcEnd != acBuf;
}

/*
 * Called by wpSetup to search KEY in the setup string and return BOOL
 * value for this KEY (TRUE - YES/Y/ON/1, FALSE - NO/N/OFF/0). If KEY not
 * found or invalid value specified for the KEY: *pfValue will not be
 * changed, result code is FALSE.
 */

SOM_Scope BOOL  SOMLINK RD_rdSetupReadBool(Rdesktop *somSelf, 
                                           PSZ pszSetupString, 
                                           PSZ pszKey, ULONG* pfValue)
{
    CHAR     acBuf[4] = { 0 };
    ULONG    cbBuf;

    cbBuf = sizeof(acBuf);
    if ( !_wpScanSetupString( somSelf, pszSetupString, pszKey, acBuf, &cbBuf ) )
      return FALSE;

    strupr( acBuf );

    switch( *((PULONG)&acBuf) )
    {
      case (ULONG)'\0SEY':    // YES
      case (ULONG)'\0\0\0Y':  // Y
      case 0x00000031:        // 1
      case (ULONG)'\0\0NO':   // ON
        *pfValue = TRUE;
        return TRUE;
    }

    switch( *((PULONG)&acBuf) )
    {
      case (ULONG)'\0\0ON':   // NO
      case (ULONG)'\0\0\0N':  // N
      case 0x00000030:        // 0
      case (ULONG)'\0FFO':    // OFF
        *pfValue = FALSE;
        return TRUE;
    }

    return FALSE;
}

/*
 * Called by wpSetup to search KEY in the setup string and return a sequence
 * number value in the list (items separated by ',', number of first item is
 * 0). If KEY not found or specified value for the KEY not listed in
 * pszValList: *pfValue will not be changed, result code is FALSE.
 */

SOM_Scope BOOL  SOMLINK RD_rdSetupReadVal(Rdesktop *somSelf, 
                                          PSZ pszSetupString, 
                                          PSZ pszKey, PSZ pszValList, 
                                          ULONG* pulValue)
{
    CHAR     acBuf[256];
    ULONG    cbBuf;
    LONG     lIdx;

    cbBuf = sizeof(acBuf);
    if ( !_wpScanSetupString( somSelf, pszSetupString, pszKey, acBuf, &cbBuf ) )
      return FALSE;

    lIdx = utilFindItem( strlen( pszValList ), pszValList, ',', acBuf );
    if ( lIdx == -1 )
      return FALSE;

    *pulValue = (ULONG)lIdx;
    return TRUE;
}

/*
 * Fills the buffer pcBuf with help file full name. The buffer size must
 * be minimum of CCHMAXPATH bytes.
 */

SOM_Scope void  SOMLINK RD_rdGetHelpFile(Rdesktop *somSelf, char* pcBuf)
{
    PCHAR        pcLastSlash;
    somId        Id;

    Id = somIdFromString( "M_Rdesktop" );
    strcpy( pcBuf,
            _somLocateClassFile( SOMClassMgrObject, Id, Rdesktop_MajorVersion,
                                 Rdesktop_MinorVersion ) );
    SOMFree( Id );
    pcLastSlash = strrchr( pcBuf, '\\' );
    if ( pcLastSlash == NULL )
      strcpy( pcBuf, HELP_FILE );
    else
      strcpy( &pcLastSlash[1], HELP_FILE );
}

SOM_Scope void  SOMLINK RD_wpInitData(Rdesktop *somSelf)
{
    RdesktopData *somThis = RdesktopGetData(somSelf);

    Rdesktop_parent_WPAbstract_wpInitData(somSelf);
    debugInit();
    cwInit( somSelf );
    prInit( somSelf );

#ifdef DEBUG_FILE
    _pszHost = (PSZ)_wpAllocMem( somSelf, 64, NULL );
//    strcpy( _pszHost, "172.26.96.142" );
    strcpy( _pszHost, "172.26.100.3" );
    _pszUser = (PSZ)_wpAllocMem( somSelf, 64, NULL );
    strcpy( _pszUser, "vasilkin_av" );
    _pszDomain = (PSZ)_wpAllocMem( somSelf, 64, NULL );
    strcpy( _pszDomain, "sakh" );
    _pszPassword = (PSZ)_wpAllocMem( somSelf, 64, NULL );
    strcpy( _pszPassword, "q1QwE2Re3-r4" );
    _fLoginPrompt       = FALSE;
#else
    _pszHost            = NULL;
    _pszUser            = NULL;
    _pszDomain          = NULL;
    _pszPassword        = NULL;
    _fLoginPrompt       = DEF_PROMPT;
#endif
    _ulSizeMode         = DEF_SIZEMODE;
    _lWidth             = DEF_WIDTH;
    _lHeight            = DEF_HEIGHT;
    _ulProportionalSize = DEF_PROPSIZE;
    _ulColorDepth       = DEF_DEPTH;
    _pszClientHost      = NULL;
    _pszLocalCP         = NULL;
    _ulEncryption       = DEF_ENC;
    _pszDiskClient      = NULL;
    _seqDiskRedir._buffer = NULL;
    _seqDiskRedir._length = 0;
    _ulClipboard        = 1; // Passive.
    _ulSwitches         = DEF_SWITCHES;
    _ulRDP5Perf         = DEF_RDP5PERF;
    _pStartData         = NULL;
    _lWinPosX           = WINPOS_NOT_CHANGED;
    _lWinPosY           = WINPOS_NOT_CHANGED;
}

SOM_Scope void  SOMLINK RD_wpUnInitData(Rdesktop *somSelf)
{
    RdesktopData *somThis = RdesktopGetData(somSelf);

    startKillAllSessions( somSelf );

    utilWPFreeMem( somSelf, _pszHost );
    utilWPFreeMem( somSelf, _pszUser );
    utilWPFreeMem( somSelf, _pszDomain );
    utilWPFreeMem( somSelf, _pszPassword );
    utilWPFreeMem( somSelf, _pszClientHost );
    utilWPFreeMem( somSelf, _pszLocalCP );

    RD_rdDiskRedirDeleteAll( somSelf );

    prDone( somSelf );
    cwDone( somSelf );
    Rdesktop_parent_WPAbstract_wpUnInitData(somSelf);

    debugDone();
}

SOM_Scope BOOL  SOMLINK RD_wpSaveState(Rdesktop *somSelf)
{
    RdesktopData *somThis = RdesktopGetData(somSelf);
    ULONG        ulIdx;
    PDISKREDIR   pDiskRedir;

    _wpSaveString( somSelf, somCN_Rdesktop, SK_HOST, _pszHost );
    _wpSaveString( somSelf, somCN_Rdesktop, SK_USER, _pszUser );
    _wpSaveString( somSelf, somCN_Rdesktop, SK_DOMAIN, _pszDomain );
    _wpSaveString( somSelf, somCN_Rdesktop, SK_PASSWORD, _pszPassword );
    _wpSaveLong( somSelf, somCN_Rdesktop, SK_LOGINPROMPT, _fLoginPrompt );
    _wpSaveLong( somSelf, somCN_Rdesktop, SK_SIZEMODE, _ulSizeMode );
    _wpSaveLong( somSelf, somCN_Rdesktop, SK_WIDTH, _lWidth );
    _wpSaveLong( somSelf, somCN_Rdesktop, SK_HEIGHT, _lHeight );
    _wpSaveLong( somSelf, somCN_Rdesktop, SK_PROPSIZE, _ulProportionalSize );
    _wpSaveLong( somSelf, somCN_Rdesktop, SK_DEPTH, _ulColorDepth );
    _wpSaveString( somSelf, somCN_Rdesktop, SK_CLIENTHOST, _pszClientHost );
    _wpSaveString( somSelf, somCN_Rdesktop, SK_LOCALCP, _pszLocalCP );
    _wpSaveLong( somSelf, somCN_Rdesktop, SK_SWITCHES, _ulSwitches );
    _wpSaveLong( somSelf, somCN_Rdesktop, SK_RDP5PREF, _ulRDP5Perf );
    _wpSaveLong( somSelf, somCN_Rdesktop, SK_ENCRYPTION, _ulEncryption );
    _wpSaveString( somSelf, somCN_Rdesktop, SK_DISKCLIENT, _pszDiskClient );

    _wpSaveLong( somSelf, somCN_Rdesktop, SK_DISKREDIR_COUNT,
                 _seqDiskRedir._length );
    for( ulIdx = 0; ulIdx < _seqDiskRedir._length; ulIdx++ )
    {
      pDiskRedir = &_seqDiskRedir._buffer[ulIdx];

      _wpSaveString( somSelf, somCN_Rdesktop, SK_DISKREDIR_NAME + ulIdx,
                     pDiskRedir->acName );
      _wpSaveString( somSelf, somCN_Rdesktop, SK_DISKREDIR_PATH + ulIdx,
                     pDiskRedir->pszPath );
    }

    _wpSaveLong( somSelf, somCN_Rdesktop, SK_CLIPBOARD, _ulClipboard );
    _wpSaveLong( somSelf, somCN_Rdesktop, SK_SOUND, _ulSound );
    _wpSaveLong( somSelf, somCN_Rdesktop, SK_SERDEVREDIR_COUNT, _cSerDevRedir );
    _wpSaveData( somSelf, somCN_Rdesktop, SK_SERDEVREDIR,
                 (PBYTE)_aulSerDevRedir, _cSerDevRedir * sizeof(ULONG) );

    if ( _lWinPosX != WINPOS_NOT_CHANGED )
      _wpSaveLong( somSelf, somCN_Rdesktop, SK_WINPOS_X, _lWinPosX );
    if ( _lWinPosY != WINPOS_NOT_CHANGED )
      _wpSaveLong( somSelf, somCN_Rdesktop, SK_WINPOS_Y, _lWinPosY );

    return (Rdesktop_parent_WPAbstract_wpSaveState(somSelf));
}

SOM_Scope BOOL  SOMLINK RD_wpRestoreState(Rdesktop *somSelf, 
                                           ULONG ulReserved)
{
    RdesktopData *somThis = RdesktopGetData(somSelf);
    ULONG        ulIdx;
    ULONG        cnt, cb;
    PDISKREDIR   pDiskRedir;

    RD_rdRestoreStringNew( somSelf, SK_HOST, &_pszHost );
    RD_rdRestoreStringNew( somSelf, SK_USER, &_pszUser );
    RD_rdRestoreStringNew( somSelf, SK_DOMAIN, &_pszDomain );
    RD_rdRestoreStringNew( somSelf, SK_PASSWORD, &_pszPassword );
    _wpRestoreLong( somSelf, somCN_Rdesktop, SK_LOGINPROMPT, &_fLoginPrompt );
    _wpRestoreLong( somSelf, somCN_Rdesktop, SK_SIZEMODE, &_ulSizeMode );
    _wpRestoreLong( somSelf, somCN_Rdesktop, SK_WIDTH, (PULONG)&_lWidth );
    _wpRestoreLong( somSelf, somCN_Rdesktop, SK_HEIGHT, (PULONG)&_lHeight );
    _wpRestoreLong( somSelf, somCN_Rdesktop, SK_PROPSIZE, &_ulProportionalSize );
    _wpRestoreLong( somSelf, somCN_Rdesktop, SK_DEPTH, &_ulColorDepth );
    RD_rdRestoreStringNew( somSelf, SK_CLIENTHOST, &_pszClientHost );
    RD_rdRestoreStringNew( somSelf, SK_LOCALCP, &_pszLocalCP );
    _wpRestoreLong( somSelf, somCN_Rdesktop, SK_SWITCHES, &_ulSwitches );
    _wpRestoreLong( somSelf, somCN_Rdesktop, SK_RDP5PREF, &_ulRDP5Perf );
    _wpRestoreLong( somSelf, somCN_Rdesktop, SK_ENCRYPTION, &_ulEncryption );
    RD_rdRestoreStringNew( somSelf, SK_DISKCLIENT, &_pszDiskClient );

    _wpRestoreLong( somSelf, somCN_Rdesktop, SK_DISKREDIR_COUNT, &cnt );
    cb = cnt * sizeof(DISKREDIR);
    _seqDiskRedir._buffer = (PDISKREDIR)_wpAllocMem( somSelf, cb, NULL );
    memset( _seqDiskRedir._buffer, 0, cb );
    _seqDiskRedir._length = 0;

    if ( _seqDiskRedir._buffer != NULL )
    {
      for( ulIdx = 0; ulIdx < cnt; ulIdx++ )
      {
        pDiskRedir = &_seqDiskRedir._buffer[_seqDiskRedir._length];
        cb = sizeof(pDiskRedir->acName);
        if ( _wpRestoreString( somSelf, somCN_Rdesktop,
                               SK_DISKREDIR_NAME + ulIdx,
                               pDiskRedir->acName, &cb )
           &&
             RD_rdRestoreStringNew( somSelf, SK_DISKREDIR_PATH + ulIdx,
                                    &pDiskRedir->pszPath ) )
          _seqDiskRedir._length++;
      }
    }

    _wpRestoreLong( somSelf, somCN_Rdesktop, SK_CLIPBOARD, &_ulClipboard );
    _wpRestoreLong( somSelf, somCN_Rdesktop, SK_SOUND, &_ulSound );

    _wpRestoreLong( somSelf, somCN_Rdesktop, SK_SERDEVREDIR_COUNT,
                    &_cSerDevRedir );
    if ( _cSerDevRedir > (sizeof(_aulSerDevRedir) / sizeof(ULONG)) )
      _cSerDevRedir = 0;
    else if ( _cSerDevRedir != 0 )
    {
      cb = sizeof(_aulSerDevRedir);
      _wpRestoreData( somSelf, somCN_Rdesktop, SK_SERDEVREDIR,
                      (PBYTE)_aulSerDevRedir, &cb );
    }

    if ( !_wpRestoreLong( somSelf, somCN_Rdesktop, SK_WINPOS_X,
                          (PULONG)&_lWinPosX ) )
      _lWinPosX = WINPOS_NOT_CHANGED;

    if ( !_wpRestoreLong( somSelf, somCN_Rdesktop, SK_WINPOS_Y,
                          (PULONG)&_lWinPosY ) )
      _lWinPosY = WINPOS_NOT_CHANGED;

    return (Rdesktop_parent_WPAbstract_wpRestoreState(somSelf, ulReserved));
}

SOM_Scope BOOL  SOMLINK RD_wpAddSettingsPages(Rdesktop *somSelf, 
                                               HWND hwndNotebook)
{
    BOOL fResult = (Rdesktop_parent_WPAbstract_wpAddSettingsPages(somSelf, 
                                                               hwndNotebook));

    _rdInsertSettingsPages( somSelf, hwndNotebook );

    return fResult;
}

SOM_Scope ULONG  SOMLINK RD_wpAddObjectWindowPage(Rdesktop *somSelf, 
                                                   HWND hwndNotebook)
{
    return (Rdesktop_parent_WPAbstract_wpAddObjectWindowPage(somSelf, 
                                                             hwndNotebook));
}

SOM_Scope BOOL  SOMLINK RD_wpSetup(Rdesktop *somSelf, PSZ pszSetupString)
{
    RdesktopData *somThis = RdesktopGetData(somSelf);
    ULONG        ulValue;
    PSZ          pszValue;

    if ( !Rdesktop_parent_WPAbstract_wpSetup(somSelf, pszSetupString) )
      return FALSE;

    RD_rdSetupStringNew( somSelf, pszSetupString, "host", &_pszHost );
    RD_rdSetupStringNew( somSelf, pszSetupString, "user", &_pszUser );
    RD_rdSetupStringNew( somSelf, pszSetupString, "domain", &_pszDomain );
    RD_rdSetupStringNew( somSelf, pszSetupString, "password", &_pszPassword );
    RD_rdSetupReadBool( somSelf, pszSetupString, "prompt", &_fLoginPrompt );
    RD_rdSetupReadVal( somSelf, pszSetupString, "sizemode",
                       "ABSOLUTE,PROPORTIONAL,FULLSCREEN", &_ulSizeMode );

    RD_rdSetupReadULong( somSelf, pszSetupString, "width", (PULONG)&_lWidth );
    RD_rdSetupReadULong( somSelf, pszSetupString, "height",(PULONG)&_lHeight );
    if ( RD_rdSetupReadULong( somSelf, pszSetupString, "proportionalsize",
                              &ulValue ) &&
         ( ulValue >= PROPSIZE_MIN ) && ( ulValue <= 100 ) )
      _ulProportionalSize = ulValue;

    RD_rdSetupReadVal( somSelf, pszSetupString, "depth", "8,15,16,24,32",
                       &_ulColorDepth );
    RD_rdSetupStringNew( somSelf, pszSetupString, "clienthost", &_pszClientHost );
    RD_rdSetupStringNew( somSelf, pszSetupString, "localcodepage", &_pszLocalCP );

    pszValue = NULL;
    if ( RD_rdSetupStringNew( somSelf, pszSetupString, "switches", &pszValue ) )
    {
      _ulSwitches = 0;

      if ( utilFindItemStr( pszValue, "RDP5" ) )
        _ulSwitches |= SWFL_RDP5;
      if ( utilFindItemStr( pszValue, "COMPRESSION" ) )
        _ulSwitches |= SWFL_COMPRESSION;
      if ( utilFindItemStr( pszValue, "PRES_BMP_CACHING" ) )
        _ulSwitches |= SWFL_PRES_BMP_CACHING;
      if ( utilFindItemStr( pszValue, "FORCE_BMP_UPD" ) )
        _ulSwitches |= SWFL_FORCE_BMP_UPD;
      if ( utilFindItemStr( pszValue, "NUMLOCK_SYNC" ) )
        _ulSwitches |= SWFL_NUMLOCK_SYNC;
      if ( utilFindItemStr( pszValue, "NO_MOTION_EVENTS" ) )
        _ulSwitches |= SWFL_NO_MOTION_EVENTS;
      if ( utilFindItemStr( pszValue, "KEEP_WIN_KEYS" ) )
        _ulSwitches |= SWFL_KEEP_WIN_KEYS;

      _wpFreeMem( somSelf, (PBYTE)pszValue );
    }

    pszValue = NULL;
    if ( RD_rdSetupStringNew( somSelf, pszSetupString, "drp5perf", &pszValue ) )
    {
      _ulRDP5Perf = 0;

      if ( utilFindItemStr( pszValue, "NO_WALLPAPER" ) )
        _ulRDP5Perf |= PERFFL_NO_WALLPAPER;
      if ( utilFindItemStr( pszValue, "NO_FULLWINDOWDRAG" ) )
        _ulRDP5Perf |= PERFFL_NO_FULLWINDOWDRAG;
      if ( utilFindItemStr( pszValue, "NO_MENUANIMATIONS" ) )
        _ulRDP5Perf |= PERFFL_NO_MENUANIMATIONS;
      if ( utilFindItemStr( pszValue, "NO_THEMING" ) )
        _ulRDP5Perf |= PERFFL_NO_THEMING;
      if ( utilFindItemStr( pszValue, "NO_CURSORSETTINGS" ) )
        _ulRDP5Perf |= PERFFL_NO_CURSORSETTINGS;
      if ( utilFindItemStr( pszValue, "ANTIALIASING" ) )
        _ulRDP5Perf |= PERFFL_ANTIALIASING;

      _wpFreeMem( somSelf, (PBYTE)pszValue );
    }

    RD_rdSetupReadVal( somSelf, pszSetupString, "encryption",
                       "FULL,NONE,LOGON", &_ulEncryption );
    RD_rdSetupReadVal( somSelf, pszSetupString, "clipboard",
                       "PRIMARY,PASSIVE,OFF", &_ulClipboard );
    RD_rdSetupReadVal( somSelf, pszSetupString, "sound",
                       "LOCAL,REMOTE,OFF", &_ulSound );

    RD_rdSetupStringNew( somSelf, pszSetupString, "diskclient",
                         &_pszDiskClient );

    pszValue = NULL;
    if ( RD_rdSetupStringNew( somSelf, pszSetupString, "disk", &pszValue ) &&
         ( pszValue != NULL ) )
    {
      ULONG  cbName, cbPath, cbList = strlen( pszValue );
      PCHAR  pcName, pcPath, pcList = pszValue;
      CHAR   acName[16], acPath[CCHMAXPATH];
      
      RD_rdDiskRedirDeleteAll( somSelf );

      while( utilSplitList( &cbList, &pcList, '=', &cbName, &pcName ) &&
             utilSplitList( &cbList, &pcList, ',', &cbPath, &pcPath ) )
      {
        if ( ( utilUnQuote( sizeof(acName), acName, cbName, pcName ) > 0 ) &&
             ( utilUnQuote( sizeof(acPath), acPath, cbPath, pcPath ) > 0 ) )
          RD_rdDiskRedirAdd( somSelf, acName, acPath );
      }

      _wpFreeMem( somSelf, (PBYTE)pszValue );
    }

    return TRUE;
}

SOM_Scope WPObject*  SOMLINK RD_wpCreateFromTemplate(Rdesktop *somSelf, 
                                                     WPFolder* folder,
                                                     BOOL fLock)
{
    return (Rdesktop_parent_WPAbstract_wpCreateFromTemplate(somSelf, 
                                                            folder, 
                                                            fLock));
}

SOM_Scope void  SOMLINK RD_wpCopiedFromTemplate(Rdesktop *somSelf)
{
    Rdesktop_wpOpen( somSelf, NULLHANDLE, OPEN_SETTINGS, 0L );

    Rdesktop_parent_WPAbstract_wpCopiedFromTemplate(somSelf);
}

SOM_Scope HWND  SOMLINK RD_wpOpen(Rdesktop *somSelf, HWND hwndCnr, 
                                   ULONG ulView, ULONG param)
{
    RdesktopData *somThis = RdesktopGetData(somSelf);
    HWND         hwnd = NULLHANDLE;

    switch( ulView )
    {
      case OPEN_RDESKTOP:
        if ( _pszHost == NULL )
          hwnd = Rdesktop_parent_WPAbstract_wpOpen( somSelf, hwndCnr, 
                                                    OPEN_SETTINGS, param );
        else
          // We cannot return real hwnd for rdesktop. Fake value HWND_DESKTOP
          // will be used ==> need to overwrite wpSwitchTo() for switches to
          // OPEN_RDESKTOP view.
          hwnd = startRD( somSelf, "M_Rdesktop" ) ? HWND_DESKTOP : NULLHANDLE;
        break;

      default:
        hwnd = Rdesktop_parent_WPAbstract_wpOpen( somSelf, hwndCnr, 
                                                  ulView, param );
        break;
    }

    return hwnd;
}

/*
 * Our wpOpen() does not returns real HWND of rdesktop's window. We have
 * only pid. We need overwrite wpSwitchTo() to support our switching for
 * OPEN_RDESKTOP view.
 */

SOM_Scope BOOL  SOMLINK RD_wpSwitchTo(Rdesktop *somSelf, ULONG View)
{
    if ( View == OPEN_RDESKTOP )
      // Try to switch to progress bar than to rdesktop window.
      return prSwitchTo( somSelf ) || startSwithTo( somSelf );

    return (Rdesktop_parent_WPAbstract_wpSwitchTo(somSelf, View));
}

SOM_Scope BOOL  SOMLINK RD_wpModifyPopupMenu(Rdesktop *somSelf, 
                                             HWND hwndMenu, HWND hwndCnr, 
                                             ULONG iPosition)
{
    HMODULE      hModule = utilGetModuleHandle();

    _wpInsertPopupMenuItems( somSelf, hwndMenu, iPosition, hModule,
                             IDMNU_RDESKTOP, 0 );

    return (Rdesktop_parent_WPAbstract_wpModifyPopupMenu( somSelf, hwndMenu,
                                                          hwndCnr, iPosition ));
}

SOM_Scope BOOL  SOMLINK RD_wpMenuItemSelected(Rdesktop *somSelf, 
                                              HWND hwndFrame, 
                                              ULONG ulMenuId)
{
#define RUN_CMD_MAX_LENGTH        (1024 * 16)
    RdesktopData *somThis = RdesktopGetData(somSelf);

    switch( ulMenuId )
    {
      case IDMI_COPYRUNCMD:
      {
        PSZ   pszText;
        BOOL  fSuccess = FALSE;
        ULONG ulRC = DosAllocSharedMem( (PPVOID)&pszText, 0, RUN_CMD_MAX_LENGTH,
                                        PAG_COMMIT | PAG_READ | PAG_WRITE |
                                        OBJ_GIVEABLE | OBJ_GETTABLE | OBJ_TILE );
        if ( ulRC != NO_ERROR )
          debug( "DosAllocSharedMem() failed, rc = %u", ulRC );
        else if ( startQueryCmd( somSelf, "M_Rdesktop", _pszUser, _pszDomain,
                       _pszPassword, FALSE, RUN_CMD_MAX_LENGTH, pszText ) <= 0 )
          debug( "startQueryCmd() failed" );
        else
        {
          HAB       hab = WinQueryAnchorBlock( HWND_DESKTOP );

          if ( !WinOpenClipbrd( hab ) )
            debug( "WinOpenClipbrd() failed" );
          else
          {    
            WinEmptyClipbrd( hab );
            fSuccess = WinSetClipbrdData( hab, (ULONG)pszText, CF_TEXT,
                                          CFI_POINTER );
            WinCloseClipbrd( hab );
          }
        }

        if ( !fSuccess )
          DosFreeMem( pszText );

        return fSuccess;
      }

      case IDMI_CONSOLE:
        return cwShow( somSelf );
    }

    return (Rdesktop_parent_WPAbstract_wpMenuItemSelected( somSelf, hwndFrame,
                                                           ulMenuId ));
}

SOM_Scope BOOL  SOMLINK RD_wpMenuItemHelpSelected(Rdesktop *somSelf, 
                                                  ULONG MenuId)
{
    ULONG        ulHelpPanelId;
    CHAR         acHelpFile[CCHMAXPATH];

    switch( MenuId )
    {
      case IDMI_COPYRUNCMD:
        ulHelpPanelId = IDHELP_MI_COPYRUNCMD;
        break;

      case IDMI_CONSOLE:
        ulHelpPanelId = IDHELP_MI_CONSOLE;
        break;

      default:
        ulHelpPanelId = 0;
        break;
    }

    if ( ulHelpPanelId != 0 )
    {
      RD_rdGetHelpFile( somSelf, acHelpFile );

      return _wpDisplayHelp( somSelf, ulHelpPanelId, acHelpFile );
    }

    return (Rdesktop_parent_WPAbstract_wpMenuItemHelpSelected(somSelf, 
                                                              MenuId));
}


SOM_Scope void  SOMLINK MRD_wpclsInitData(M_Rdesktop *somSelf)
{
    M_Rdesktop_parent_M_WPAbstract_wpclsInitData(somSelf);
}

SOM_Scope void  SOMLINK MRD_wpclsUnInitData(M_Rdesktop *somSelf)
{
    M_Rdesktop_parent_M_WPAbstract_wpclsUnInitData(somSelf);
}

SOM_Scope ULONG  SOMLINK MRD_wpclsQueryIconData(M_Rdesktop *somSelf, 
                                                 PICONINFO pIconInfo)
{
    // provide own icon for all object instances of this class
    if ( pIconInfo != NULL )
    {
      pIconInfo->fFormat = ICON_RESOURCE;
      pIconInfo->hmod    = utilGetModuleHandle();
      pIconInfo->resid   = IDRES_ICON;
    }
    return sizeof(ICONINFO);
}

SOM_Scope PSZ  SOMLINK MRD_wpclsQueryTitle(M_Rdesktop *somSelf)
{
    return "rdesktop";
}

SOM_Scope ULONG  SOMLINK MRD_wpclsQueryStyle(M_Rdesktop *somSelf)
{
    return CLSSTYLE_NEVERPRINT;
}

SOM_Scope BOOL  SOMLINK MRD_wpclsCreateDefaultTemplates(M_Rdesktop *somSelf, 
                                                         WPObject* Folder)
{
#ifdef DEBUG_FILE
    // TRUE - do not create template for the class.
    return TRUE;
#else
    return FALSE;
#endif
}

SOM_Scope ULONG  SOMLINK MRD_wpclsQueryDefaultView(M_Rdesktop *somSelf)
{
    return OPEN_RDESKTOP;
}
